---
title: "assignment 6 task 2"
author: "Hollie Pennington"
date: "11/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install packages
library(tidyverse)
library(here)
library(janitor)
library(broom)
library(kableExtra)
```

```{r}
#read in data and convert to lower snake case
survey <- read_csv(here("data", "conservation_survey.csv")) %>% 
  clean_names()
```

```{r}
#make subset set only keeping conservative or liberal values 

c_or_l <- survey %>%
  select ("env_id", "pol_or") %>% 
  filter(pol_or %in% c("1", "2", "3", "5", "6", "7")) %>% 
  #convert to words instead of value
  mutate(pol_or = case_when(
    pol_or %in% c(1,2,3) ~ "Conservative",
    pol_or %in% c(5,6,7) ~ "Liberal"
  )) %>% #
  mutate(env_id = case_when(
    env_id %in% 1 ~ "Yes", 
    env_id %in% 2 ~ "No", 
    env_id %in% 3 ~ "Unsure"
  )) %>% 
  na.omit()
```

```{r}
#find count
c_or_l %>% 
  count(pol_or) 
```

```{r}
#make table of count vs env id
pol_count <- c_or_l %>% 
  janitor::tabyl(pol_or, env_id) 

#add proportions
pol_pc <- pol_count %>% 
  janitor::adorn_percentages() %>% 
  adorn_pct_formatting(digits = 2) %>% 
  adorn_ns()
```

```{r}
#use KableExtra to create table that will show up in knitted document
pol_pc %>% 
  kable(col.names = c("Political Party", 
                      "No", 
                      "Unsure",
                      "Yes"), 
        caption = "**Table 1: Political Affiliation and Environmentalism:** Below shows a the amount of conservatives and liberals who self identify as an environmentalist. Data was collected from an online survery and all political affiliations that were not liberal or conservative were excluded from the table. The counts represent that amount of people who answered the question or percent represents the proportions of the specific political group."
  )
```

 
```{r}
#convert to contingency table
pol_count_ct <- pol_count %>%
  column_to_rownames(var = "pol_or")
pol_count_ct
```


