---
title: "Task 4"
author: "Hollie Pennington"
date: "12/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.align = "center")
library(tidyverse)
library(here)
library(janitor)
```

```{r}
mono_lake <- read_csv(here("data", "mono_lake_annual_levels.csv"), 
                      skip = 5) %>% 
  clean_names()
```

```{r}
ggplot(data = mono_lake, aes(x = year, y = lake_level_feet_above_sea_level )) + 
  geom_line(size = 2, 
            color = "blue") + 
  geom_ribbon(aes(ymin = -Inf, ymax = lake_level_feet_above_sea_level), 
              fill = "lightblue") +
  geom_hline(yintercept = 6377,
             color = "orange", 
             size = 1.5,
             alpha = 0.5) + 
  geom_vline(xintercept = 1987, 
             linetype = "dashed") +
  geom_hline(yintercept = 6350, 
             color = "yellow", 
             size = 1.5, 
             alpha = 0.5) +
  labs (title = "Annual water level at Mono Lake (CA)", 
        x = "Year", 
        y = "Feet above sea level") + 
  theme_test() + 
  theme(plot.title = element_text(hjust = 0.5, 
                                  color = "darkblue")) + 
  theme(axis.title.y = element_text(color = "darkblue")) + 
  theme(axis.title.x = element_text(color = "darkblue")) + 
  theme(axis.text = element_text(color = "blue"), 
        axis.line.x.top = element_line(color = "darkblue")) + 
  theme(panel.border = element_rect(color = "darkblue")) + 
  theme(panel.background = element_rect("grey"))
```




