---
title: "Task 3"
author: "Hollie Pennington"
date: "12/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(broom)
library(kableExtra)
library(ggbeeswarm)
library(effsize)
```

```{r}
#read in data, clean up data, and select variables for project
lizards_2 <- read_csv(here("data", "lizards.csv")) %>% 
  clean_names() %>% 
  select(spp, sex, total_length) %>% 
  filter(sex == "F") %>% 
  filter(spp == c("CNUN", "CNTE")) %>% 
  mutate(spp = case_when(
    spp == "CNUN" ~ "C. uniparens", 
    spp == "CNTE" ~ "C. tessalatus"
  ))
```

```{r}
ggplot() + 
  geom_beeswarm(data = lizards_2, 
                aes(x = spp, 
                    y = total_length, 
                    color = spp), 
                show.legend = FALSE)+ 
  labs(title = "Length of female lizards by species", 
       x = "Species", 
       y = "Total Length (mm)") + 
  theme_minimal()
```

```{r}
#summary table with mean, standard deviation, and sample size 

lizards_stats <- lizards_2 %>% 
  group_by(spp) %>% 
  summarise(mean = mean(total_length, na.rm = TRUE),
            standard_deviation = sd(total_length, na.rm = TRUE),
            sample_size = n())
```

```{r}
#make table into table can see on knitted document 
lizards_stats %>%
  kable(col.names = c("Species", "Mean (mm)", "Standard Deviation (mm)", "Sample Size"), 
        caption = "<b> Table 1: <b> The table compares the mean (mm), standard deviation, and sample size between female lizard species.") %>% 
          kable_styling(full_width = FALSE)
```

```{r, include = FALSE}
# exploratory plots 
ggplot(data = lizards_2, aes (x = total_length)) + 
  geom_histogram(bins = 30) + 
  facet_wrap(~ spp)

ggplot(data = lizards_2, aes(sample = total_length)) + 
  geom_qq() + 
  facet_wrap(~ spp)

# depending on the bin size the data is normally distributed. The smaller the bin size the more skewed to the left the C. tessaltus is. 
```

```{r}
#statistical testing: cohen's d 
# "CNUN" = "C. uniparens", 
# "CNTE" = "C. tessalatus"

CNUN <- lizards_2 %>% 
  filter(spp == "C. uniparens") %>% 
  pull(total_length)

CNTE <- lizards_2 %>% 
  filter(spp == "C. tessalatus") %>% 
  pull(total_length)

cd_lizards <- cohen.d(CNUN, CNTE, na.rm = TRUE)

cd_lizards
```
